SET IDENTITY_INSERT [dbo].[Subcategoria] ON
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (2, 2, N'Florales                                          ', N'Plantas que dan color y vida al jardín                                                              ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (3, 2, N'Frutales                                          ', N'Perfectas para cultivar tu propia comida                                                            ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (4, 2, N'Decorativas                                       ', N'Desde arbustos hasta arboles para dar mayor diversidad al jardín                                    ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (5, 3, N'Herramientas                                      ', N'Todo para hacer de tu experiencia en la jardinería más sencilla.                                    ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (6, 3, N'Macetas                                           ', N'Las flores también necesitan un hogar y aquí puedes encontrar el indicado.                          ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (7, 3, N'Riego                                             ', N'Un buen sistema de riego es fundamental para el crecimiento de cualquier planta.                    ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (8, 3, N'Decoraciones                                      ', N'Un jardín es mucho más que solo plantas y flores, checa nuestras decoraciones.                      ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (9, 4, N'Abonos Naturales                                  ', N'El alimento perfecto para cualquier planta.                                                         ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (10, 4, N'Abonos Artificiales                               ', N'Los mejores productos químicos que proporcionan nutrientes a tu jardín.                             ')
INSERT INTO [dbo].[Subcategoria] ([id_subcategoria], [id_categoria], [nombre_subcategoria], [descripcion_subcategoria]) VALUES (11, 4, N'Pesticidas                                        ', N'Productos para evitar que invitados no deseados ataquen tu jardín.                                  ')
SET IDENTITY_INSERT [dbo].[Subcategoria] OFF
